---
files: ^
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=200']
      - id: check-ast
      - id: fix-byte-order-marker
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: name-tests-test
        args: ['--django']
      - id: sort-simple-yaml

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.1
    hooks:
      - id: mypy
        additional_dependencies:
          - 'types-requests==2.28.11.4'
          - 'types-urllib3==1.26.25.3'
          - 'numpy==1.22.4'
        pass_filenames: false

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.253'
    hooks:
      - id: ruff

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        name: black
        entry: black
        args: ['--check']
        language: python
        require_serial: true
        types_or: [python, pyi]
